[package]
name = "day18"
version = "0.1.0"
authors = ["jtempest"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
fnv = "1.0.6"
