[package]
name = "day15"
version = "0.1.0"
authors = ["jtempest"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
itertools = "0.8.2"